### ISSUE TITLE
Issue with openvc.loadiamge

### ISSUE THREAD

**Issue by f41ardu** [atduskgreg/opencv-processing#101]
All examples using videos won't work on my installation (win 8.1/ latest version of Processing. 
Add check video.width and heigth solve my issue. 
I'm not sure if thia is also an issue using an external camera.

  image(video, 0, 0); 
  if (video.width > 0 && video.height > 0) {//check if the cam instance has loaded pixels
   opencv.loadImage(video);
  }

**Comment by atduskgreg** [comment]
It sounds like you're calling this before the video frames are actually available. Check out the background subtraction example for the right way to do this.
