### ISSUE TITLE
Processing 3 does not accept variables in size() so many examples won't run

### ISSUE THREAD

**Issue by marcolabreu** [atduskgreg/opencv-processing#102]
In Processing 3 is not possible to use the function `size()` with variables. Since many examples that come with **opencv-processing** set the size using images or video sizes as variables (like in `size(opencv.width, opencv.height);`), the examples will not run.

The simplest solution I found is to replace any `size()` by `surface.setSize()` and keep everything else unchanged, including the variables. Basically `size(opencv.width, opencv.height);` becomes `surface.setSize(opencv.width, opencv.height);` and the code runs without any further mods in Processing 3.

Sorry for just pointing to the problem instead of offering more help, but I really don't have any relevant experience with code and I started using Processing this very week. And I don't know if the code altered like that will still work Processing 2 or if not using `size()` has any drawbacks.

Anyway, brilliant software, kudos!

PS: when `size()` is used to set the mode, like in `size(2*opencv.width, opencv.height, P2D);` (HSVColorTracking.pde), it's necessary to delete the string, not accepted by `surface.setSize()`. Since P2D is the default mode, may I assume there is no harm?

**Comment by atduskgreg** [comment]
closed as of 21135f2e632838381898535cfd06f0243e4c186e and release 0.5.4
