### ISSUE TITLE
Display contours over image 

### ISSUE THREAD

**Issue by heaversm** [atduskgreg/opencv-processing#112]
Hi - how would you display the contours of an image over the image itself? It seems it is applying a solid background color below the contours themselves. 

![edges](https://user-images.githubusercontent.com/520541/50379136-bdbe4300-05f5-11e9-9fcc-df296c2d3c08.gif)

```
import gab.opencv.*;
import processing.video.Capture;

OpenCV opencv;
Capture cam;

int zoom = 2;
int size = 3;
boolean invert = false;

// input resolution
int w = 160 * size, h = 120 * size;
//int w = 1080, h = 720;

void setup() {
  size(960, 720);
  
  // init cam
  cam = new Capture(this, w, h);
  cam.start();
  
  // init opencv
  opencv = new OpenCV(this, w, h);
  
}


void draw() {
  
  opencv.loadImage(cam);
  
  scale(zoom);
  
  //webcam image
  PImage src = snapshot("original", 0, 0);
  
  //edges
  opencv.findCannyEdges(120, 75);
  if(invert) opencv.invert();
  snapshot("canny", 0, 0);

}


// read a new frame when it's available
void captureEvent(Capture c) {
  c.read();
}


// create a snapshot and display it
PImage snapshot(String label, int px, int py) {  
  
  // show image
  PImage img = opencv.getSnapshot();
  
  if (label != "canny"){
    //
  }
  
  if (label == "canny"){
    if (invert){
      image(img, 0,0);
    }
  } else {
    image(img, 0,0);
  }
  
 
  // image outline
  noFill(); 
  stroke(invert ? 0 : 255); 
  //rect(px * w, py * h, w, h);
  
  // return the snapshot so we can reuse it
  return img;
}


void keyPressed() {
  invert = !invert; 
}
```

**Comment by atduskgreg** [comment]
A couple of things. First you haven’t found the contours in this example. You’ve run a canny filter on the image. Finding contours returns you actual geometric information about the locations of the contours in data. You can then use this data to draw lines on top of the image if you want. See the find contours example to see usage: https://github.com/atduskgreg/opencv-processing/tree/master/examples/FindContours (also installed in processing with the library). 

If instead you want to just draw the filtered image you’ve produced here on top of the image from the camera that’s a task that has nothing to do with OpenCV directly. See the processing documentation for more on how to do that: https://processing.org/reference/blendMode_.html
