### ISSUE TITLE
Upgrade to 2.4.7

### ISSUE THREAD

**Issue by atduskgreg** [atduskgreg/opencv-processing#42]
And, more generally, improve system for updating to a new OpenCV build so it doesn't seem so difficult.

**Comment by philworthy** [comment]
Hi @atduskgreg do you have any plans to upgrade to support the OpenCV 3 beta? They have added some cool stuff with 'long term optical tracking' which I think would be really useful in a lot of CV projects. Thanks

**Comment by atduskgreg** [comment]
@philworthy That's definitely something I'd like to do. The only stopper on my side is getting the builds for all of the platforms that we support. I wouldn't want to screw up windows, linux, or arm support (platforms that we got working with the help of a lot of great contributions from @jmwohl, @P0ulp, @kylemcdonald, @arturoc, etc). And since it's a little difficult for me to test effectively on all those platforms I'm waiting a bit on OpenCV 3 support until I have time to create an test builds on all of those platforms. This is an area where pull requests and contributions are more than welcome, they're needed.

**Comment by hristod** [comment]
Any luck with this?

**Comment by atduskgreg** [comment]
I only work on this library very occasionally nowadays as I don't use opencv in my day-to-day work. I'd love a contribution that upgraded the whole thing to opencv 3.x but I'm not the person to do it ay the moment.
