### ISSUE TITLE
examples size() parameter use needs to be changed.

### ISSUE THREAD

**Issue by kasperkamperman** [atduskgreg/opencv-processing#80]
Processing doesn't allow variables anymore as parameter. This is used a lot in the examples `size(opencv.width, opencv.height/2);`

This gives the following error message:
![screen shot 2015-06-10 at 16 50 16](https://cloud.githubusercontent.com/assets/1760616/8085544/02f7ed04-0f91-11e5-8a50-63dcaf01e775.png)

Processing 3.0a10

**Comment by clankill3r** [comment]
Yeah the new size method really sucks.

**Comment by nonsequitoria** [comment]
A simple fix for all examples that use variables in the size call is to change from something like this:

`size(opencv.width + opencv.width/4 + 30, opencv.height)`

to this:

`surface.setResizable(true);
  surface.setSize(opencv.width + opencv.width/4 + 30, opencv.height);`

**Comment by atduskgreg** [comment]
closed as of 21135f2e632838381898535cfd06f0243e4c186e and release 0.5.4
