### ISSUE TITLE
import processing.core.* error

### ISSUE THREAD

**Issue by hhhaiai** [atduskgreg/opencv-processing#83]
java using  processing.core.*   happen errors!

where is   processing.core.*??

and   what's launch about *.pde？？？？

**Comment by evgeniy-storozhenko** [comment]
+1
Could you tell, where can I get **PImage**, **PApplet** and other stuff from processing?

**Comment by evgeniy-storozhenko** [comment]
I found. This is Processing Development Environment (PDE) http://processing.org.
Sources: https://github.com/processing/processing

**Comment by atduskgreg** [comment]
This is a library for the processing environment. Are you trying to use it outside of that?
