### ISSUE TITLE
Can't seem to install the OpenCV file into processing ...

### ISSUE THREAD

**Issue by kevinpmcclellan** [atduskgreg/opencv-processing#86]
Greg,

I know this is totally a newbie thing. I've tried all I can to get it installed and have looked through all the forums. Additionally I have uninstalled Processing several times.

Not sure what I am doing wrong. Please help.

Thank you!
Kevin

**Comment by atduskgreg** [comment]
As of release 0.5.4 it should be available in the contribution manager in the Processing app again. 

Sketch > Import Library > Add Library

Search for "opencv" in the search box.
