### ISSUE TITLE
i think we have a bug!

### ISSUE THREAD

**Issue by FrankOcean11** [atduskgreg/opencv-processing#91]
so i run the face detection sketch from opencv and i get a black screen on the pop up when before i used to get either the front camera or the back one lately i been trying to connect using my new usb webcam with no luck ONLY on this opencv for processing because it does work on all resolutions using the capture library but when i use the opencv in the list of capture devices i do see it BUT i dont see all the resolutions im being offered by the capture folder under examples finally i started getting this msg on the ide

"(java.exe:5768): GStreamer-CRITICAL **: 
Trying to dispose element rgb, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element."

this is the code i ran

import gab.opencv.*;
import processing.video.*;
import java.awt.Rectangle;

Capture video;
OpenCV opencv;

Rectangle[] faces;

void setup() {
  size(640, 480);
  video = new Capture(this, 640,480,Capture.list()[20]);
  opencv = new OpenCV(this, 640/2, 480/2);
  opencv.loadCascade(OpenCV.CASCADE_FRONTALFACE); 
  faces = opencv.detect();
  video.start();
}

void draw() {
  scale(2);
  opencv.loadImage(video);

  image(video, 0, 0 );

  noFill();
  stroke(0, 255, 0);
  strokeWeight(3);
  Rectangle[] faces = opencv.detect();
  println(faces.length);

  for (int i = 0; i < faces.length; i++) {
    println(faces[i].x + "," + faces[i].y);
    rect(faces[i].x, faces[i].y, faces[i].width, faces[i].height);
  }
}
void captureEvent(Capture c) {
  c.read();
}

maybe you can run this code and test/replicate the errors but note that you must use a usb hub in order to get the Array elements shown by the Capture.list()[] as my device usually comes in at element 20 thru 24 in all sorts of res  like such 

Available cameras:
name=Microsoft LifeCam Rear,size=640x360,fps=30
name=Microsoft LifeCam Rear,size=640x480,fps=30
name=Microsoft LifeCam Rear,size=424x240,fps=15
name=Microsoft LifeCam Rear,size=424x240,fps=30
name=Microsoft LifeCam Rear,size=320x240,fps=15
name=Microsoft LifeCam Rear,size=320x240,fps=30
name=Microsoft LifeCam Rear,size=320x180,fps=15
name=Microsoft LifeCam Rear,size=320x180,fps=30
name=Microsoft LifeCam Rear,size=160x120,fps=15
name=Microsoft LifeCam Rear,size=160x120,fps=30
name=Microsoft LifeCam Rear,size=1280x800,fps=5
name=Microsoft LifeCam Rear,size=1280x720,fps=30
name=Microsoft LifeCam Rear,size=960x544,fps=30
name=Microsoft LifeCam Rear,size=848x480,fps=30
name=Microsoft LifeCam Rear,size=960x544,fps=15
name=Microsoft LifeCam Rear,size=848x480,fps=30
name=Microsoft LifeCam Rear,size=640x360,fps=30
name=Microsoft LifeCam Rear,size=640x480,fps=30

name=USB2.0 Camera,size=320x240,fps=4 //
name=USB2.0 Camera,size=160x120,fps=15 // as you can see i only get 2 res options when i used to get like 4 or 5

name=Microsoft LifeCam Front,size=640x360,fps=30
name=Microsoft LifeCam Front,size=640x480,fps=30
name=Microsoft LifeCam Front,size=424x240,fps=15
name=Microsoft LifeCam Front,size=424x240,fps=30
name=Microsoft LifeCam Front,size=320x240,fps=15
name=Microsoft LifeCam Front,size=320x240,fps=30
name=Microsoft LifeCam Front,size=320x180,fps=15
name=Microsoft LifeCam Front,size=320x180,fps=30
name=Microsoft LifeCam Front,size=160x120,fps=15
name=Microsoft LifeCam Front,size=160x120,fps=30
name=Microsoft LifeCam Front,size=1280x800,fps=5
name=Microsoft LifeCam Front,size=1280x720,fps=30
name=Microsoft LifeCam Front,size=960x544,fps=30
name=Microsoft LifeCam Front,size=848x480,fps=30
name=Microsoft LifeCam Front,size=960x544,fps=15
name=Microsoft LifeCam Front,size=848x480,fps=30
name=Microsoft LifeCam Front,size=640x360,fps=30
name=Microsoft LifeCam Front,size=640x480,fps=30

i seriously think theres a bug not to mention that i been reading in the forums and im not the only one with this issue "black screen" and im not the only one with the usb external cam issues

**Comment by jorditost** [comment]
@FrankOcean11 check my answer in [this other thread](https://github.com/atduskgreg/opencv-processing/issues/90). The way you are calling the Capture constructor is incorrect.

If the problem persists, can you be more specific? For example, when you write *when before i used to get*, what do you mean with BEFORE? It works with the front and rear built-in cameras but it is not working with your new USB camera? Or did it always work (with a previous version of opencv-processing or Processing) and it's not working anymore?

**Comment by FrankOcean11** [comment]
problem solved i did a reInstallation and cleaned out my Reg files in my pc tho i do see some issues with resolution or zoom when i use   cam = new Capture(this, 640, 480, "USB2.0 Camera");   
 and   video = new Capture(this, 640, 480, "USB2.0 Camera");   

<img width="905" alt="screenshot 59" src="https://cloud.githubusercontent.com/assets/10504709/11429798/30f389b8-944b-11e5-9014-d864f978efaa.png">
